name: CI Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
  # Only trigger, when the Build (Tests) workflow successed
  workflow_run:
    workflows: ["CI build"]
    types: [completed]
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy the APP
        run: echo "Deploy the APP"
